{% set name = "langsmith" %}
{% set version = "0.2.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/langsmith-{{ version }}.tar.gz
  sha256: 0996d12622b56ff21414ab8b5c16cbe3ff389a3668fa3fd1d82475bd57e5bc9e

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  entry_points:
    - langsmith = langsmith.cli.main:main

requirements:
  host:
    - python {{ python_min }}
    - poetry-core
    - pip
  run:
    - python >={{ python_min }},<4.0
    - pydantic >=1,<3
    - requests >=2.0.0,<3.0.0
    - orjson >=3.9.14,<4.0.0
    - httpx >=0.23.0,<1
    - requests-toolbelt >=1.0.0,<2.0.0

test:
  imports:
    - langsmith
    - langsmith.schemas
    - langsmith.client
  commands:
    - pip check
    - langsmith -h
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://smith.langchain.com/
  summary: Client library to connect to the LangSmith language model tracing and evaluation API.
  description: |
    LangSmith helps you visualize and evaluate language model applications to help you build better
    performing applications. This is the client library to connect to the LangSmith API.
  license: MIT
  license_family: MIT
  license_file: LICENSE
  doc_url: https://docs.smith.langchain.com/docs/
  dev_url: https://github.com/langchain-ai/langchainplus-sdk

extra:
  recipe-maintainers:
    - pavelzw
    - hinthornw
    - vowelparrot
